### ISSUE TITLE
Can I help XPocket

### ISSUE THREAD

**Issue by caspervanneck** [XPocket/XPocket#10]
Can I help you with XPocket

**Comment by XtremePlayzCODE** [comment]
?

**Comment by caspervanneck** [comment]
I can dev from XPocket

**Comment by caspervanneck** [comment]
@XtremePlayzCODE  
I can travis testing and a CircleCI download site

**Comment by XtremePlayzCODE** [comment]
let me think

**Comment by daniktheboss** [comment]
First do it

**Comment by daniktheboss** [comment]
Off topic but... how can I write php code to create a .yml file with code in it if its not there?

**Comment by XtremePlayzCODE** [comment]
lol it is very easy to do

**Comment by XtremePlayzCODE** [comment]
well you already helped so yes you may

**Comment by daniktheboss** [comment]
So can u tell me?

**Comment by daniktheboss** [comment]
Can you tell me how to write the code?

**Comment by daniktheboss** [comment]
If its easy pls help!?

**Comment by XtremePlayzCODE** [comment]
check if the file exists and if not create it and write to it. simple

**Comment by daniktheboss** [comment]
K

**Comment by daniktheboss** [comment]
Hey, mind helping me? Go to my repositories. I started a mcpe server with python! Need some help :D

**Comment by XtremePlayzCODE** [comment]
php to python... tf

**Comment by XtremePlayzCODE** [comment]
need access man

**Comment by daniktheboss** [comment]
What? Python is fast, easy to code, easy to understand! Not real hard to do. Will you help?

**Comment by XtremePlayzCODE** [comment]
sure man

**Comment by XtremePlayzCODE** [comment]
look at my issue i opened

**Comment by daniktheboss** [comment]
Hey, how are u going to read the class alphaconfig:?

**Comment by XtremePlayzCODE** [comment]
AlphaConfig:? its AlphaConfig. you dont know python lmao

**Comment by daniktheboss** [comment]
Go to your page and to config file! You write with :

**Comment by XtremePlayzCODE** [comment]
thats what your supposed to fucking do

**Comment by daniktheboss** [comment]
Why do u keep on cussing?

**Comment by XtremePlayzCODE** [comment]
because im getting mad

**Comment by daniktheboss** [comment]
Well calm down then!

**Comment by XtremePlayzCODE** [comment]
WHY THE FUCK ARE YOU COMPLAINGING IM USING A FUCKING : THATS WHAT YOUR SUPPOSED TO DO

**Comment by XtremePlayzCODE** [comment]
Ok, illl calm down but can you help me

**Comment by daniktheboss** [comment]
We can just make a new branch python 3

**Comment by XtremePlayzCODE** [comment]
I need help finding sys.py

**Comment by daniktheboss** [comment]
Sys.py?

**Comment by XtremePlayzCODE** [comment]
yes sys.py the sys module from ppythpn

**Comment by daniktheboss** [comment]
Idk
